apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: "POST"
      manageAlerts: true
      alertmanagerUid: "alertmanager"
      prometheusType: "Prometheus"
      prometheusVersion: "2.45.0"
      cacheLevel: "High"
      disableRecordingRules: false
      incrementalQueryOverlapWindow: "10m"
    secureJsonData: {}
    version: 1
    readOnly: false

  - name: MLflow Metrics
    type: prometheus
    access: proxy
    url: http://mlflow:5000/metrics
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "10s"
      queryTimeout: "60s"
      httpMethod: "GET"
    secureJsonData: {}
    version: 1
    readOnly: false

  - name: Kafka Metrics
    type: prometheus
    access: proxy
    url: http://kafka:9090/metrics
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "30s"
      httpMethod: "GET"
    secureJsonData: {}
    version: 1
    readOnly: false

  - name: Prefect Metrics
    type: prometheus
    access: proxy
    url: http://prefect-server:4200/metrics
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "GET"
    secureJsonData: {}
    version: 1
    readOnly: false 